services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "mp_PruebaA3"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 10

  fiscalia-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fiscalia-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: mp_PruebaA3
      DB_NAME: master
    depends_on:
      sqlserver:
        condition: service_healthy

  fiscalia-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fiscalia-frontend
    ports:
      - "8080:80"
    depends_on:
      - fiscalia-backend
